#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : speex
Version  : dsp
Release  : 3
URL      : http://downloads.xiph.org/releases/speex/speexdsp-1.2rc3.tar.gz
Source0  : http://downloads.xiph.org/releases/speex/speexdsp-1.2rc3.tar.gz
Summary  : An open-source, patent-free speech codec
Group    : Development/Tools
License  : BSD-3-Clause
Requires: speex-lib
Requires: speex-data
BuildRequires : pkgconfig(fftw3f)

%description
Speex is a patent-free audio codec designed especially for voice (unlike 
Vorbis which targets general audio) signals and providing good narrowband 
and wideband quality. This project aims to be complementary to the Vorbis
codec.

%package data
Summary: data components for the speex package.
Group: Data

%description data
data components for the speex package.


%package dev
Summary: dev components for the speex package.
Group: Development
Requires: speex-lib
Requires: speex-data
Provides: speex-devel

%description dev
dev components for the speex package.


%package lib
Summary: lib components for the speex package.
Group: Libraries
Requires: speex-data

%description lib
lib components for the speex package.


%prep
%setup -q -n speexdsp-1.2rc3

%build
export LANG=C
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffast-math -falign-functions=32 -fno-semantic-interposition -ftree-loop-vectorize "
export FCFLAGS="$CFLAGS -O3 -ffast-math -falign-functions=32 -fno-semantic-interposition -ftree-loop-vectorize "
export FFLAGS="$CFLAGS -O3 -ffast-math -falign-functions=32 -fno-semantic-interposition -ftree-loop-vectorize "
export CXXFLAGS="$CXXFLAGS -O3 -ffast-math -falign-functions=32 -fno-semantic-interposition -ftree-loop-vectorize "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/doc/speexdsp/manual.pdf

%files dev
%defattr(-,root,root,-)
/usr/include/speex/speex_echo.h
/usr/include/speex/speex_jitter.h
/usr/include/speex/speex_preprocess.h
/usr/include/speex/speex_resampler.h
/usr/include/speex/speexdsp_config_types.h
/usr/include/speex/speexdsp_types.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
